#
#    ┌─────────────────────────────────────────────────────────────────┐
#    │                                                                 │
#    │                _   ___                 _                 _      │
#    │    ___ _ _ ___| |_|_  |  ___   ___ ___| |_ _ _ _ ___ ___| |_    │
#    │   | . | | |   | '_|_| |_|   |_|   | -_|  _| | | | . |  _| '_|   │
#    │   |_  |___|_|_|_,_|_____|_|_|_|_|_|___|_| |_____|___|_| |_,_|   │
#    │   |___|                                                         │
#    │                                                                 │
#    └─────────────────────────────────────────────────────────────────┘
#

---

services:
  t-web:
    image: ghcr.io/eugeny/tabby-web:${TW_VERSION_TAG}
    container_name: t-web
    restart: always
    user: ${TW_PUID}:${TW_PGID}
    depends_on:
      - t-db
    ports:
      - ${TW_PORT}:${TW_PORT}
    environment:
      - PUID=${TW_PUID}
      - PGID=${TW_PGID}
      - DATABASE_URL=mysql://root:${TW_MARIADB_PASSWORD}@t-db/${TW_MARIADB_DATABASE}
      - PORT=${TW_PORT}
      - DEBUG=${TW_DEBUG}
      - DOCKERIZE_ARGS=-wait tcp://t-db:3306 -timeout 60s
      - SOCIAL_AUTH_GITHUB_KEY=${TW_SOCIAL_AUTH_GITHUB_KEY}
      - SOCIAL_AUTH_GITHUB_SECRET=${TW_SOCIAL_AUTH_GITHUB_SECRET}
      - APP_DIST_STORAGE=file:///app-dist

  t-db:
    image: mariadb:${MARIADB_VERSION_TAG}
    container_name: t-db
    restart: always
    environment:
      MARIADB_DATABASE: ${TW_MARIADB_DATABASE}
      MARIADB_USER: ${TW_MARIADB_USER}
      MARIADB_PASSWORD: ${TW_MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TW_MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  t-cgw:
    image: ghcr.io/eugeny/tabby-connection-gateway:${TWCG_VERSION_TAG}
    container_name: t-cgw
    environment:
      - TABBY_AUTH_TOKEN=${TWCG_AUTH_TOKEN}
    ports:
      - ${TWCG_PORT}:${TWCG_PORT}
    command: --token-auth --host ${TWCG_HOST_IP}

volumes:
  db:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}