# 
#   █▀▀ █▄░█ ▀█▀ █░█░█ █▀█ █▄▀ █▀ █▀█ ▄▀█ █▀▀ █▀▀
#   █▄█ █░▀█ ░█░ ▀▄▀▄▀ █▀▄ █░█ ▄█ █▀▀ █▀█ █▄▄ ██▄
# 
# ---info--
# https://docs.n8n.io/hosting/installation/docker/#using-with-postgresql
# https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgres
#

#     {
#       "type": 3,
#       "title": "n8n",
#       "description": "Example of self-hosting n8n in various environments like docker, kubernetes, etc.",
#       "note": "https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgresAndWorker | https://docs.n8n.io/hosting/installation/docker/",
#       "categories": [
#         "Ansible"
#       ],
#       "platform": "linux",
#       "logo": "https://avatars.githubusercontent.com/u/45487711?s=48&v=4",
#       "repository": {
#         "url": "https://github.com/gunk1n/gn-portainer-teplates",
#         "stackfile": "stacks/n8n/docker-compose.yml"
#       },
#       "env": [
#         {
#           "name": "N8N_PORT",
#           "label": "N8N_PORT",
#           "description": "...",
#           "default": "5678"
#         },
#         {
#           "name": "N8N_TIMEZONE",
#           "label": "N8N_TIMEZONE",
#           "description": "...",
#           "default": "Europe/Moscow"
#         },
#         {
#           "name": "POSTGRES_USER",
#           "label": "POSTGRES_USER",
#           "description": "...",
#           "default": "postgres"
#         },
#         {
#           "name": "POSTGRES_PASSWORD",
#           "label": "POSTGRES_PASSWORD",
#           "description": "..",
#           "default": "a9s8jtc67s9datjc7"
#         },
#         {
#           "name": "POSTGRES_DB",
#           "label": "POSTGRES_DB",
#           "description": "...",
#           "default": "n8n"
#         },
#         {
#           "name": "POSTGRES_NON_ROOT_USER",
#           "label": "POSTGRES_NON_ROOT_USER",
#           "description": "...",
#           "default": "n8n"
#         },
#         {
#           "name": "POSTGRES_NON_ROOT_PASSWORD",
#           "label": "POSTGRES_NON_ROOT_PASSWORD",
#           "description": "...",
#           "default": "ct345cy563u623w4"
#         },
#         {
#           "name": "NETWORK_NAME",
#           "label": "Name of the network to which applications are connected",
#           "description": "...",
#           "default": ""
#         }
#       ],
#       "maintainer": "https://github.com/gunk1n/gn-portainer-teplates"
#     }

---

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE="${N8N_TIMEZONE}"
      - TZ="${N8N_TIMEZONE}"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - ${N8N_PORT}:5678
    links:
      - postgres
    volumes:
      - storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_storage:
  storage:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
