# 
#   █▀▀ █▄░█ ▀█▀ █░█░█ █▀█ █▄▀ █▀ █▀█ ▄▀█ █▀▀ █▀▀
#   █▄█ █░▀█ ░█░ ▀▄▀▄▀ █▀▄ █░█ ▄█ █▀▀ █▀█ █▄▄ ██▄
# 
# ---info--
# https://docs.n8n.io/hosting/installation/docker/#using-with-postgresql
# https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgres
#

---

volumes:
  db_storage:
  n8n_storage:
  redis_storage:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}

x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DB}
    - DB_POSTGRESDB_USER=${N8N_POSTGRES_NON_ROOT_USER}
    - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_NON_ROOT_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
  links:
    - postgres
    - redis
  volumes:
    - n8n_storage:/home/node/.n8n
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres_n8n:
    image: postgres:${N8N_POSTGRES_IMAGE_VERSION}
    restart: always
    environment:
      - N8N_POSTGRES_USER
      - N8N_POSTGRES_PASSWORD
      - N8N_POSTGRES_DB
      - N8N_POSTGRES_NON_ROOT_USER
      - N8N_POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - n8n_db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${N8N_POSTGRES_USER} -d ${N8N_POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_IMAGE_VERSION}
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres_n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DB}
      - DB_POSTGRESDB_USER=${N8N_POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - ${N8N_PORT}:5678
    links:
      - postgres_n8n
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
<<<<<<< HEAD
      postgres_n8n:
        condition: service_healthy

volumes:
  n8n_db_storage:
  n8n_storage:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
=======
      - n8n
>>>>>>> 0102b8f5fc86f90d79ccfbaf3b4fd594b9dc0e02
