#!/bin/bash
set -e;

if [ -n "${N8N_POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${N8N_POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$N8N_POSTGRES_USER" --dbname "$N8N_POSTGRES_DB" <<-EOSQL
		CREATE USER ${N8N_POSTGRES_NON_ROOT_USER} WITH PASSWORD '${N8N_POSTGRES_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${N8N_POSTGRES_DB} TO ${N8N_POSTGRES_NON_ROOT_USER};
		GRANT CREATE ON SCHEMA public TO ${N8N_POSTGRES_NON_ROOT_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi