# 
#    ┌─────────────────────────────────────────────────────────────────┐
#    │                                                                 │
#    │                _   ___                 _                 _      │
#    │    ___ _ _ ___| |_|_  |  ___   ___ ___| |_ _ _ _ ___ ___| |_    │
#    │   | . | | |   | '_|_| |_|   |_|   | -_|  _| | | | . |  _| '_|   │
#    │   |_  |___|_|_|_,_|_____|_|_|_|_|_|___|_| |_____|___|_| |_,_|   │
#    │   |___|                                                         │
#    │                                                                 │
#    └─────────────────────────────────────────────────────────────────┘
# 

---

#
# IP Renewal
# By default, Tor automatically changes IPs every 10 minutes. You can manually renew the IP by restarting the container:
#   $ docker restart tor-socks-proxy
#
# Checking the Proxy Status and logs
#   $ docker logs tor-socks-proxy
#
# Configuring a Client to Use the Proxy
#   $ curl --socks5-hostname 127.0.0.1:9150 https://ipinfo.tw/ip
#

services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    image: peterdavehello/tor-socks-proxy:latest
    restart: unless-stopped
    ports:
      - '{{ TOR_DNS_PORT }}:53/udp'
      - '{{ TOR_SOCKS5_PORT }}:9150/tcp'

volumes:
  data:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
